# Generated by Django 3.0.3 on 2020-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='categorys',
            field=models.ManyToManyField(to='movies.category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_pop',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_vote',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
