# Generated by Django 3.0.3 on 2020-03-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200228_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='movies.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_ids',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_lang',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
