# Generated by Django 3.0.3 on 2020-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200301_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
