# Generated by Django 3.0.3 on 2020-03-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='lists',
        ),
    ]
